//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen_UnidadMedida
    {
        public int id_almacen { get; set; }
        public int id_unidadMedida { get; set; }
        public int capacidad { get; set; }
        public System.DateTime fechaCaptura { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
