//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.Almacen_UnidadMedida = new HashSet<Almacen_UnidadMedida>();
            this.Indicador_Capacidad = new HashSet<Indicador_Capacidad>();
        }
    
        public int id_almacen { get; set; }
        public string nombre { get; set; }
        public int id_planta { get; set; }
        public int id_tipoAlmacen { get; set; }
    
        public virtual Planta Planta { get; set; }
        public virtual TipoAlmacen TipoAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Almacen_UnidadMedida> Almacen_UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador_Capacidad> Indicador_Capacidad { get; set; }
    }
}
