//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraIndicador
    {
        public long Indice { get; set; }
        public long IndiceIndicador { get; set; }
        public long IndiceUsuario { get; set; }
        public int IndiceMovimiento { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual BitacoraMovimientosIndicador BitacoraMovimientosIndicador { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
