//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long id { get; set; }
        public string error { get; set; }
        public Nullable<long> idUsuario { get; set; }
        public string seccion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
