//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Indicador_Laboratorio = new HashSet<Indicador_Laboratorio>();
        }
    
        public int id_equipo { get; set; }
        public int id_planta { get; set; }
        public int id_laboratorio { get; set; }
        public string nombre { get; set; }
        public int duracion { get; set; }
    
        public virtual Laboratorio Laboratorio { get; set; }
        public virtual Planta Planta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador_Laboratorio> Indicador_Laboratorio { get; set; }
    }
}
