//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Indicador_Laboratorio = new HashSet<Indicador_Laboratorio>();
        }
    
        public int id_equipo { get; set; }
        public int id_planta { get; set; }
        public int id_laboratorio { get; set; }
        public string nombre { get; set; }
        public int duracion { get; set; }
    
        public virtual Laboratorio Laboratorio { get; set; }
        public virtual Planta Planta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador_Laboratorio> Indicador_Laboratorio { get; set; }
    }
}
