//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador_V2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicador_V2()
        {
            this.IndicadorParo_V2 = new HashSet<IndicadorParo_V2>();
            this.IndicadorRechazo_V2 = new HashSet<IndicadorRechazo_V2>();
        }
    
        public long Indice { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Orden { get; set; }
        public string Lote { get; set; }
        public string Maquina { get; set; }
        public string Reales { get; set; }
        public string Ciclo { get; set; }
        public string Turno { get; set; }
        public string Material { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IndiceVelocidad { get; set; }
        public Nullable<long> IndiceProceso { get; set; }
    
        public virtual IndicadorVelocidad_V2 IndicadorVelocidad_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicadorParo_V2> IndicadorParo_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicadorRechazo_V2> IndicadorRechazo_V2 { get; set; }
        public virtual Proceso Proceso { get; set; }
    }
}
