//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorParo_V2
    {
        public long IndiceIndicador { get; set; }
        public long IndiceParo { get; set; }
        public int Cantidad { get; set; }
        public string Folio { get; set; }
        public bool EsParoPlanificado { get; set; }
    
        public virtual Indicador_V2 Indicador_V2 { get; set; }
        public virtual Paro Paro { get; set; }
    }
}
