//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorTiempo_V2
    {
        public long IndiceProceso { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Proceso Proceso { get; set; }
    }
}
