//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicador()
        {
            this.Indicador_Paro = new HashSet<Indicador_Paro>();
            this.Indicador_Rechazo = new HashSet<Indicador_Rechazo>();
        }
    
        public long id_indicador { get; set; }
        public string orden { get; set; }
        public string lote { get; set; }
        public string maquina { get; set; }
        public string reales { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string turno { get; set; }
        public string ciclo { get; set; }
        public Nullable<long> id_proceso { get; set; }
        public Nullable<long> id_velocidad { get; set; }
        public string material { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador_Paro> Indicador_Paro { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual Proceso_Velocidad Proceso_Velocidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador_Rechazo> Indicador_Rechazo { get; set; }
    }
}
