//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorParo_V2
    {
        public long IndiceIndicador { get; set; }
        public long IndiceParo { get; set; }
        public int Cantidad { get; set; }
        public string Folio { get; set; }
        public bool EsParoPlanificado { get; set; }
    
        public virtual Indicador_V2 Indicador_V2 { get; set; }
        public virtual Paro Paro { get; set; }
    }
}
