//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador_Paro
    {
        public long id_indicador { get; set; }
        public long id_paro { get; set; }
        public Nullable<long> cantidad { get; set; }
        public string Folio { get; set; }
    
        public virtual Indicador Indicador { get; set; }
        public virtual Paro Paro { get; set; }
    }
}
