//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador_Servicio
    {
        public int id_indicadorServicio { get; set; }
        public int id_planta { get; set; }
        public int id_servicio { get; set; }
        public int id_equipo { get; set; }
        public int capacidad_real { get; set; }
        public int capacidad_historica { get; set; }
        public System.DateTime fecha_captura { get; set; }
    }
}
