//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador_Tiempo
    {
        public long id_proceso { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
    
        public virtual Proceso Proceso { get; set; }
    }
}
