//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paro()
        {
            this.Indicador_Paro = new HashSet<Indicador_Paro>();
            this.IndicadorParo_V2 = new HashSet<IndicadorParo_V2>();
            this.Paro1 = new HashSet<Paro>();
            this.ParosPlaneadosMes_V2 = new HashSet<ParosPlaneadosMes_V2>();
        }
    
        public long id_paro { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<long> paro_padre { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> id_proceso { get; set; }
        public Nullable<byte> programado { get; set; }
        public Nullable<byte> eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador_Paro> Indicador_Paro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicadorParo_V2> IndicadorParo_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paro> Paro1 { get; set; }
        public virtual Paro Paro2 { get; set; }
        public virtual Proceso Proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParosPlaneadosMes_V2> ParosPlaneadosMes_V2 { get; set; }
    }
}
