//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso_UsuariosMensaje
    {
        public long id_proceso { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> email { get; set; }
        public Nullable<bool> sms { get; set; }
        public Nullable<int> alerta_paros { get; set; }
        public Nullable<int> alerta_horas { get; set; }
        public Nullable<int> alerta_oee { get; set; }
        public Nullable<bool> alerta_lote { get; set; }
        public Nullable<bool> alerta_lote_maq_internacional { get; set; }
    
        public virtual Proceso Proceso { get; set; }
    }
}
