//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proceso()
        {
            this.Indicador = new HashSet<Indicador>();
            this.Indicador_V2 = new HashSet<Indicador_V2>();
            this.IndicadorVelocidad_V2 = new HashSet<IndicadorVelocidad_V2>();
            this.Paro = new HashSet<Paro>();
            this.ParosPlaneadosMes_V2 = new HashSet<ParosPlaneadosMes_V2>();
            this.Proceso_UsuariosMensaje = new HashSet<Proceso_UsuariosMensaje>();
            this.Proceso_Velocidad = new HashSet<Proceso_Velocidad>();
            this.Departamento = new HashSet<Departamento>();
            this.Rechazo = new HashSet<Rechazo>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public long id_proceso { get; set; }
        public string nombre { get; set; }
        public Nullable<long> id_linea { get; set; }
        public Nullable<byte> eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador> Indicador { get; set; }
        public virtual Indicador_Tiempo Indicador_Tiempo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador_V2> Indicador_V2 { get; set; }
        public virtual IndicadorTiempo_V2 IndicadorTiempo_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicadorVelocidad_V2> IndicadorVelocidad_V2 { get; set; }
        public virtual Linea Linea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paro> Paro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParosPlaneadosMes_V2> ParosPlaneadosMes_V2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proceso_UsuariosMensaje> Proceso_UsuariosMensaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proceso_Velocidad> Proceso_Velocidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamento> Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechazo> Rechazo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
