//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso_UsuariosMensaje
    {
        public long id_proceso { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> email { get; set; }
        public Nullable<bool> sms { get; set; }
        public Nullable<int> alerta_paros { get; set; }
        public Nullable<int> alerta_horas { get; set; }
        public Nullable<int> alerta_oee { get; set; }
        public Nullable<bool> alerta_lote { get; set; }
        public Nullable<bool> alerta_lote_maq_internacional { get; set; }
    
        public virtual Proceso Proceso { get; set; }
    }
}
