//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioCapacidad
    {
        public int id_usuarioCapacidad { get; set; }
        public long id_usuario { get; set; }
        public string tipo { get; set; }
        public int id_objeto { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
