//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioCapacidad
    {
        public int id_usuarioCapacidad { get; set; }
        public long id_usuario { get; set; }
        public string tipo { get; set; }
        public int id_objeto { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
