//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_grafica_indicadores
    {
        public string agrupador { get; set; }
        public Nullable<System.DateTime> FRECUENCIA { get; set; }
        public Nullable<long> id_proceso { get; set; }
        public Nullable<long> CICLOS { get; set; }
        public Nullable<long> PIEZAS_STD { get; set; }
        public Nullable<long> PIEZAS_PRODUCIDAS_REAL { get; set; }
        public Nullable<long> PIEZAS_PRODUCIDAS { get; set; }
        public long PAROS_TOTALES { get; set; }
        public long RECHAZOS_TOTALES { get; set; }
        public string turno { get; set; }
        public string orden { get; set; }
        public string lote { get; set; }
        public Nullable<int> velocidad { get; set; }
        public long id_linea { get; set; }
        public long id_departamento { get; set; }
        public int id_centro { get; set; }
        public long id_velocidad { get; set; }
    }
}
