//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_paros_programados_V2
    {
        public string agrupador { get; set; }
        public Nullable<System.DateTime> FRECUENCIA { get; set; }
        public Nullable<long> IndiceProceso { get; set; }
        public long PAROS_TOTALES { get; set; }
    }
}
