//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_paros_programados
    {
        public string agrupador { get; set; }
        public Nullable<System.DateTime> FRECUENCIA { get; set; }
        public Nullable<long> id_proceso { get; set; }
        public long PAROS_TOTALES { get; set; }
    }
}
