//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_paros
    {
        public long id_indicador { get; set; }
        public long id_paro { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<long> paro_padre { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> id_proceso { get; set; }
        public Nullable<byte> eliminado { get; set; }
        public Nullable<long> cantidad { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string turno { get; set; }
        public Nullable<long> id_velocidad { get; set; }
    }
}
