//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_usuarios
    {
        public long id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> ultimo_ingreso { get; set; }
        public Nullable<System.DateTime> ultima_renovacion { get; set; }
        public Nullable<byte> directorio_activo { get; set; }
        public Nullable<byte> eliminado { get; set; }
        public string DescripcionPerfil { get; set; }
        public string DescripcionSeccion { get; set; }
        public string Url { get; set; }
    }
}
