//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_usuarios_procesos
    {
        public long IndiceUsuario { get; set; }
        public long IndiceProceso { get; set; }
        public string NombreProceso { get; set; }
        public long IndiceLinea { get; set; }
        public string NombreLinea { get; set; }
        public long IndiceDepartamento { get; set; }
        public string NombreDepartamento { get; set; }
        public int IndiceCentro { get; set; }
        public string NombreCentro { get; set; }
    }
}
