//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_usuarios
    {
        public long id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> ultimo_ingreso { get; set; }
        public Nullable<System.DateTime> ultima_renovacion { get; set; }
        public Nullable<byte> directorio_activo { get; set; }
        public Nullable<byte> eliminado { get; set; }
        public string DescripcionPerfil { get; set; }
        public string DescripcionSeccion { get; set; }
        public string Url { get; set; }
    }
}
