//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndicadoresOEE.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_usuarios_procesos
    {
        public long id_usuario { get; set; }
        public long id_proceso { get; set; }
        public string nombre_proceso { get; set; }
        public long id_linea { get; set; }
        public string nombre_linea { get; set; }
        public long id_departamento { get; set; }
        public string nombre_depto { get; set; }
        public int id_centro { get; set; }
        public string nombre_centro { get; set; }
    }
}
